# SPARCED exp
# Sandbox based on SPARCED standard
# Last update: 2024-11-19

# General infos
name: SPARCED_exp
running_wild: False
location: "data"
# Compilation
compilation:
    root: "model"
    files:
      compartments: "legacy_Compartments.txt"
      observables: "legacy_Observables.txt"
      omics_data: "legacy_OmicsData.txt"
      output_parameters: "output_parameters.txt"  # This file is generated upon compilation
      ratelaws: "legacy_noStoicMat_Ratelaws.txt"
      species: "legacy_Species.txt"
# Simulation
simulation:
    root: "simulation"    
    files:
      gene_regulation: "legacy_GeneReg.txt"
      omics_data: "legacy_OmicsData.txt"
    experiment:
      root: "experiment"
      file: "experiment.yaml"

