# SPARCED exp
# Sandbox based on SPARCED standard
# Last update: 2024-11-21

# General infos
name: SPARCED_exp
running_wild: False
location: "data"
# Compilation
compilation:
    directory: "model"
    compartments:
      file: "compartments.tsv"
      id: "standard"
    files:
      observables: "legacy_Observables.txt"
      output_parameters: "output_parameters.txt"  # This file is generated upon compilation
      ratelaws: "legacy_noStoicMat_Ratelaws.txt"
      species: "legacy_Species.txt"
# Simulation
simulation:
    directory: "simulation"    
    files:
      gene_regulation: "legacy_GeneReg.txt"
      omics_data: "legacy_OmicsData.txt"
    experiment:
      directory: "experiment"
      file: "experiment.yaml"

